package com.kreezcraft.morebeautifulbuttons.recipes;

import com.kreezcraft.morebeautifulbuttons.blocks.InitBlocks;
import com.kreezcraft.morebeautifulbuttons.items.InitItems;

import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.IRecipe;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.registry.ForgeRegistries;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraft.util.ResourceLocation;

public class ModRecipes {

	public static void init() {
		//GameRegistry.addSmelting(InitBlocks.DIAMOND_SAND, new ItemStack(InitBlocks.DIAMOND_GLASS), 10f);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.ACACIA_BUTTON), new ItemStack(Blocks.PLANKS,1,4), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.ACACIA_LOG_BUTTON), new ItemStack(Blocks.LOG2,1,0), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BIRCH_BUTTON), new ItemStack(Blocks.PLANKS,1,2), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BIRCH_LOG_BUTTON), new ItemStack(Blocks.LOG,1,2), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BLACK_SHULKER_BOX_BUTTON), Blocks.BLACK_SHULKER_BOX, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BLACK_STAINED_GLASS_BUTTON), new ItemStack(Blocks.STAINED_GLASS,1,15), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BLACK_TERRACOTTA_BUTTON), new ItemStack(Blocks.STAINED_HARDENED_CLAY,1,15), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BLACK_WOOL_BUTTON), new ItemStack(Blocks.WOOL,1,15), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BLOCK_OF_QUARTZ_BUTTON), new ItemStack(Blocks.QUARTZ_BLOCK,1,0), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BLUE_SHULKER_BOX_BUTTON), Blocks.BLUE_SHULKER_BOX, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BLUE_STAINED_GLASS_BUTTON), new ItemStack(Blocks.STAINED_GLASS,1,11), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BLUE_TERRACOTTA_BUTTON), new ItemStack(Blocks.STAINED_HARDENED_CLAY,1,11), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BLUE_WOOL_BUTTON), new ItemStack(Blocks.WOOL,1,11), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BONE_BLOCK_BUTTON), Blocks.BONE_BLOCK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BOOKSHELF_BUTTON), Blocks.BOOKSHELF, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BRICKS_BUTTON), Blocks.BRICK_BLOCK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BROWN_MUSHROOM_BLOCK_BUTTON), Blocks.BROWN_MUSHROOM_BLOCK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BROWN_SHULKER_BOX_BUTTON), Blocks.BROWN_SHULKER_BOX, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BROWN_STAINED_GLASS_BUTTON), new ItemStack(Blocks.STAINED_GLASS,1,12), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BROWN_TERRACOTTA_BUTTON), new ItemStack(Blocks.STAINED_HARDENED_CLAY,1,12), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.BROWN_WOOL_BUTTON), new ItemStack(Blocks.WOOL,1,12), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.CACTUS_BUTTON), Blocks.CACTUS, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.CHISELED_QUARTZ_BLOCK_BUTTON), new ItemStack(Blocks.QUARTZ_BLOCK,1,1), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.CHISELED_RED_SANDSTONE_BUTTON), new ItemStack(Blocks.RED_SANDSTONE,1,1), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.CHISELED_SANDSTONE_BUTTON), new ItemStack(Blocks.SANDSTONE,1,1), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.CHISELED_STONE_BRICKS_BUTTON), new ItemStack(Blocks.STONEBRICK,1,3), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.CHORUS_FLOWER_BUTTON), Blocks.CHORUS_FLOWER, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.CHORUS_PLANT_BUTTON), Blocks.CHORUS_PLANT, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.CLAY_BUTTON), Blocks.CLAY, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.COARSE_DIRT_BUTTON), new ItemStack(Blocks.DIRT,1,1), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.COBBLESTONE_BUTTON), Blocks.COBBLESTONE, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.CRACKED_STONE_BRICKS_BUTTON), new ItemStack(Blocks.STONEBRICK,1,2), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.CYAN_SHULKER_BOX_BUTTON), Blocks.CYAN_SHULKER_BOX, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.CYAN_STAINED_GLASS_BUTTON), new ItemStack(Blocks.STAINED_GLASS,1,9), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.CYAN_TERRACOTTA_BUTTON), new ItemStack(Blocks.STAINED_HARDENED_CLAY,1,9), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.CYAN_WOOL_BUTTON), new ItemStack(Blocks.WOOL,1,9), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.DARK_OAK_BUTTON), new ItemStack(Blocks.PLANKS,1,5), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.DARK_OAK_LOG_BUTTON), new ItemStack(Blocks.LOG2,1,1), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.DARK_PRISMARINE_BUTTON), new ItemStack(Blocks.PRISMARINE,1,2), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.DIAMOND_BLOCK_BUTTON), Blocks.DIAMOND_BLOCK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.DIAMOND_ORE_BUTTON), Blocks.DIAMOND_ORE, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.DIRT_BUTTON), new ItemStack(Blocks.DIRT,1,0), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.EMERALD_BLOCK_BUTTON), Blocks.EMERALD_BLOCK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.EMERALD_ORE_BUTTON), Blocks.EMERALD_ORE, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.END_STONE_BUTTON), Blocks.END_STONE, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.END_STONE_BRICKS_BUTTON), Blocks.END_BRICKS, InitItems.BUTTON_PRESS);
		
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.GLASS_BUTTON), Blocks.GLASS, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.GLOWSTONE_BUTTON), Blocks.GLOWSTONE, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.GOLD_BLOCK_BUTTON), Blocks.GOLD_BLOCK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.GOLD_ORE_BUTTON), Blocks.GOLD_ORE, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.GRAVEL_BUTTON), Blocks.GRAVEL, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.GRAY_SHULKER_BOX_BUTTON), Blocks.GRAY_SHULKER_BOX, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.GRAY_STAINED_GLASS_BUTTON), new ItemStack(Blocks.STAINED_GLASS,1,7), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.GRAY_TERRACOTTA_BUTTON), new ItemStack(Blocks.STAINED_HARDENED_CLAY,1,7), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.GRAY_WOOL_BUTTON), new ItemStack(Blocks.WOOL,1,7), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.GREEN_SHULKER_BOX_BUTTON), Blocks.GREEN_SHULKER_BOX, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.GREEN_STAINED_GLASS_BUTTON), new ItemStack(Blocks.STAINED_GLASS,1,13), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.GREEN_TERRACOTTA_BUTTON), new ItemStack(Blocks.STAINED_HARDENED_CLAY,1,13), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.GREEN_WOOL_BUTTON), new ItemStack(Blocks.WOOL,1,13), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.YELLOW_WOOL_BUTTON), new ItemStack(Blocks.WOOL,1,4), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.YELLOW_STAINED_GLASS_BUTTON), new ItemStack(Blocks.STAINED_GLASS,1,4), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.YELLOW_TERRACOTTA_BUTTON), new ItemStack(Blocks.STAINED_HARDENED_CLAY,1,4), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.YELLOW_SHULKER_BOX_BUTTON), new ItemStack(Blocks.YELLOW_SHULKER_BOX), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.SLIME_BUTTON), new ItemStack(Blocks.SLIME_BLOCK), InitItems.BUTTON_PRESS);

		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.HARDENED_CLAY_BUTTON), new ItemStack(Blocks.HARDENED_CLAY), InitItems.BUTTON_PRESS);

		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.HAY_BLOCK_BUTTON), Blocks.HAY_BLOCK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.ICE_BUTTON), Blocks.ICE, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.IRON_BLOCK_BUTTON), Blocks.IRON_BLOCK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.IRON_ORE_BUTTON), Blocks.IRON_ORE, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.JUNGLE_BUTTON), new ItemStack(Blocks.PLANKS,1,3), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.JUNGLE_LOG_BUTTON), new ItemStack(Blocks.LOG,1,3), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.LAPIS_BLOCK_BUTTON), Blocks.LAPIS_BLOCK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.LAPIS_ORE_BUTTON), Blocks.LAPIS_ORE, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.LIGHT_BLUE_SHULKER_BOX_BUTTON), Blocks.LIGHT_BLUE_SHULKER_BOX, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.LIGHT_BLUE_STAINED_GLASS_BUTTON), new ItemStack(Blocks.STAINED_GLASS,1,3), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.LIGHT_BLUE_TERRACOTTA_BUTTON), new ItemStack(Blocks.STAINED_HARDENED_CLAY,1,3), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.LIGHT_BLUE_WOOL_BUTTON), new ItemStack(Blocks.WOOL,1,3), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.LIGHT_GRAY_SHULKER_BOX_BUTTON), Blocks.SILVER_SHULKER_BOX, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.LIGHT_GRAY_STAINED_GLASS_BUTTON), new ItemStack(Blocks.STAINED_GLASS,1,8), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.LIGHT_GRAY_TERRACOTTA_BUTTON), new ItemStack(Blocks.STAINED_HARDENED_CLAY,1,8), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.LIGHT_GRAY_WOOL_BUTTON), new ItemStack(Blocks.WOOL,1,8), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.LIME_SHULKER_BOX_BUTTON), Blocks.LIME_SHULKER_BOX, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.LIME_STAINED_GLASS_BUTTON), new ItemStack(Blocks.STAINED_GLASS,1,5), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.LIME_TERRACOTTA_BUTTON), new ItemStack(Blocks.STAINED_HARDENED_CLAY,1,5), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.LIME_WOOL_BUTTON), new ItemStack(Blocks.WOOL,1,5), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.MAGENTA_SHULKER_BOX_BUTTON), Blocks.MAGENTA_SHULKER_BOX, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.MAGENTA_STAINED_GLASS_BUTTON), new ItemStack(Blocks.STAINED_GLASS,1,2), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.MAGENTA_TERRACOTTA_BUTTON), new ItemStack(Blocks.STAINED_HARDENED_CLAY,1,2), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.MAGENTA_WOOL_BUTTON), new ItemStack(Blocks.WOOL,1,2), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.MAGMA_BUTTON), Blocks.MAGMA, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.MELON_BLOCK_BUTTON), Blocks.MELON_BLOCK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.MOSSY_COBBLESTONE_BUTTON), Blocks.MOSSY_COBBLESTONE, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.MOSSY_STONE_BRICKS_BUTTON), new ItemStack(Blocks.STONEBRICK,1,1), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.MYCELIUM_BUTTON), Blocks.MYCELIUM, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.NETHER_BRICKS_BUTTON), Blocks.NETHER_BRICK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.NETHER_WART_BLOCK_BUTTON), Blocks.NETHER_WART_BLOCK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.NETHERRACK_BUTTON), Blocks.NETHERRACK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.OAK_LOG_BUTTON), new ItemStack(Blocks.LOG,1,0), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.OBSIDIAN_BUTTON), Blocks.OBSIDIAN, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.ORANGE_SHULKER_BOX_BUTTON), Blocks.ORANGE_SHULKER_BOX, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.ORANGE_STAINED_GLASS_BUTTON), new ItemStack(Blocks.STAINED_GLASS,1,1), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.ORANGE_TERRACOTTA_BUTTON), new ItemStack(Blocks.STAINED_HARDENED_CLAY,1,1), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.ORANGE_WOOL_BUTTON), new ItemStack(Blocks.WOOL,1,1), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.PACKED_ICE_BUTTON), Blocks.PACKED_ICE, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.PILLAR_QUARTZ_BLOCK_BUTTON), new ItemStack(Blocks.QUARTZ_BLOCK,1,2), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.PINK_SHULKER_BOX_BUTTON), Blocks.PINK_SHULKER_BOX, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.PINK_STAINED_GLASS_BUTTON), new ItemStack(Blocks.STAINED_GLASS,1,6), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.PINK_TERRACOTTA_BUTTON), new ItemStack(Blocks.STAINED_HARDENED_CLAY,1,6), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.PINK_WOOL_BUTTON), new ItemStack(Blocks.WOOL,1,6), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.PRISMARINE_BRICKS_BUTTON), new ItemStack(Blocks.PRISMARINE,1,1), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.PRISMARINE_BUTTON), new ItemStack(Blocks.PRISMARINE,1,0), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.PUMPKIN_BUTTON), Blocks.PUMPKIN, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.PURPLE_SHULKER_BOX_BUTTON), Blocks.PURPLE_SHULKER_BOX, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.PURPLE_STAINED_GLASS_BUTTON), new ItemStack(Blocks.STAINED_GLASS,1,10), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.PURPLE_TERRACOTTA_BUTTON), new ItemStack(Blocks.STAINED_HARDENED_CLAY,1,10), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.PURPLE_WOOL_BUTTON), new ItemStack(Blocks.WOOL,1,10), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.PURPUR_BLOCK_BUTTON), Blocks.PURPUR_BLOCK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.PURPUR_PILLAR_BUTTON), Blocks.PURPUR_PILLAR, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.QUARTZ_ORE_BUTTON), Blocks.QUARTZ_ORE, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.RED_MUSHROOM_BLOCK_BUTTON), Blocks.RED_MUSHROOM_BLOCK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.RED_NETHER_BRICKS_BUTTON), Blocks.RED_NETHER_BRICK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.RED_SAND_BUTTON), new ItemStack(Blocks.SAND,1,1), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.RED_SANDSTONE_BUTTON), new ItemStack(Blocks.RED_SANDSTONE,1,0), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.RED_SHULKER_BOX_BUTTON), Blocks.RED_SHULKER_BOX, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.RED_STAINED_GLASS_BUTTON), new ItemStack(Blocks.STAINED_GLASS,1,14), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.RED_TERRACOTTA_BUTTON), new ItemStack(Blocks.STAINED_HARDENED_CLAY,1,14), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.RED_WOOL_BUTTON), new ItemStack(Blocks.WOOL,1,14), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.REDSTONE_BLOCK_BUTTON), Blocks.REDSTONE_BLOCK, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.REDSTONE_ORE_BUTTON), Blocks.REDSTONE_ORE, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.SAND_BUTTON), new ItemStack(Blocks.SAND,1,0), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.SANDSTONE_BUTTON), new ItemStack(Blocks.SANDSTONE,1,0), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.SEA_LANTERN_BUTTON), Blocks.SEA_LANTERN, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.SMOOTH_RED_SANDSTONE_BUTTON), new ItemStack(Blocks.RED_SANDSTONE,1,2), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.SMOOTH_SANDSTONE_BUTTON), new ItemStack(Blocks.SANDSTONE,1,2), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.SNOW_BUTTON), Blocks.SNOW, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.SOUL_SAND_BUTTON), Blocks.SOUL_SAND, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.SPONGE_BUTTON), new ItemStack(Blocks.SPONGE,1,0), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.SPRUCE_BUTTON), new ItemStack(Blocks.PLANKS,1,1), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.SPRUCE_LOG_BUTTON), new ItemStack(Blocks.LOG,1,1), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.STONE_ANDESITE_BUTTON), new ItemStack(Blocks.STONE,1,5), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.STONE_ANDESITE_SMOOTH_BUTTON), new ItemStack(Blocks.STONE,1,6), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.STONE_BRICKS_BUTTON), new ItemStack(Blocks.STONEBRICK,1,0), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.STONE_DIORITE_BUTTON), new ItemStack(Blocks.STONE,1,3), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.STONE_DIORITE_SMOOTH_BUTTON), new ItemStack(Blocks.STONE,1,4), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.STONE_GRANITE_BUTTON), new ItemStack(Blocks.STONE,1,1), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.STONE_GRANITE_SMOOTH_BUTTON), new ItemStack(Blocks.STONE,1,2), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.WET_SPONGE_BUTTON), new ItemStack(Blocks.SPONGE,1,1), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.WHITE_SHULKER_BOX_BUTTON), Blocks.WHITE_SHULKER_BOX, InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.WHITE_STAINED_GLASS_BUTTON), new ItemStack(Blocks.STAINED_GLASS,1,0), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.WHITE_TERRACOTTA_BUTTON), new ItemStack(Blocks.STAINED_HARDENED_CLAY,1,0), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.WHITE_WOOL_BUTTON), new ItemStack(Blocks.WOOL,1,0), InitItems.BUTTON_PRESS);
		GameRegistry.addShapelessRecipe(new ItemStack(InitBlocks.WOODEN_BUTTON), new ItemStack(Blocks.PLANKS,1,0), InitItems.BUTTON_PRESS);

		GameRegistry.addShapedRecipe(new ItemStack(InitItems.BUTTON_PRESS), "xxx","x x","xxx",'x',Items.STICK);
	}

}
